TI2Project/TI2Project/Models/Estudios.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TI2Project.Models{

    public class Estudios{
        public Estudios()
        {
            ListaDeFilmes= new HashSet<Filmes>();
        }

        //atributos de cada estúdio: id, nome e imagem
        public int ID { get; set; }

        [Required(ErrorMessage = "Write studio's name.")]
        [Display(Name = "Name")]
        public string Nome { get; set; }

        [Display(Name = "Image")]
        public string Imagem { get; set; }

        public virtual ICollection<Filmes> ListaDeFilmes { get; set; } //filmes produzidos pelo estúdio
    }
}

TI2Project/TI2Project/Controllers/EstudiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TI2Project.Models;

namespace TI2Project.Controllers
{
    public class EstudiosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Estudios
        public ActionResult Index()
        {
            return View(db.Estudios.ToList());
        }

        // GET: Estudios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Estudios estudio = db.Estudios.Find(id);
            if (estudio == null)
            {
                return RedirectToAction("Index");
            }
            return View(estudio);
        }

        // GET: Estudios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estudios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome")] Estudios estudio, HttpPostedFileBase foto)
        {

            string caminho = "";
            bool ficheiroValido = false;

            if (foto == null)
            {
                estudio.Imagem = "no_image.png";
            }
            else
            {
                string mimeType = foto.ContentType;

                if (mimeType == "image/jpeg" || mimeType == "image/png")
                {
                    Guid g;
                    g = Guid.NewGuid();

                    string extensao = Path.GetExtension(foto.FileName).ToLower();

                    string nomeFicheiro = g.ToString() + extensao;

                    caminho = Path.Combine(Server.MapPath("~/Images/Studios/"), nomeFicheiro);

                    estudio.Imagem = nomeFicheiro;

                    ficheiroValido = true;
                }
                else
                {
                    estudio.Imagem = "no_image.png";
                }
            }

            if (ModelState.IsValid)
            {

                try
                {
                    db.Estudios.Add(estudio);
                    db.SaveChanges();

                    if (ficheiroValido) foto.SaveAs(caminho);

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }


               
              
            }

            return View(estudio);
        }

        // GET: Estudios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Estudios estudios = db.Estudios.Find(id);
            if (estudios == null)
            {
                return RedirectToAction("Index");
            }
            return View(estudios);
        }

        // POST: Estudios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome")] Estudios estudio, HttpPostedFileBase foto)
        {

            string caminho = "";
            bool ficheiroValido = false;

            if (foto == null)
            {
                estudio.Imagem = "no_image.png";
            }
            else
            {
                string mimeType = foto.ContentType;

                if (mimeType == "image/jpeg" || mimeType == "image/png")
                {
                    Guid g;
                    g = Guid.NewGuid();

                    string extensao = Path.GetExtension(foto.FileName).ToLower();

                    string nomeFicheiro = g.ToString() + extensao;

                    caminho = Path.Combine(Server.MapPath("~/Images/Studios/"), nomeFicheiro);

                    estudio.Imagem = nomeFicheiro;

                    ficheiroValido = true;
                }
                else
                {
                    estudio.Imagem = "no_image.png";
                }
            }

            if (ModelState.IsValid)
            {

                try
                {
                    db.Entry(estudio).State = EntityState.Modified;
                    db.SaveChanges();

                    if (ficheiroValido) foto.SaveAs(caminho);

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }

                


            }
        return View(estudio);
        }

        // GET: Estudios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Estudios estudio = db.Estudios.Find(id);
            if (estudio == null)
            {
                return RedirectToAction("Index");
            }
            return View(estudio);
        }

        // POST: Estudios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estudios estudio = db.Estudios.Find(id);
            db.Estudios.Remove(estudio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TI2Project/TI2Project/Views/Estudios/Create.cshtml
@model TI2Project.Models.Estudios

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Estudios", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estudios</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="foto" />
                @*@Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TI2Project/TI2Project/Views/Estudios/Delete.cshtml
@model TI2Project.Models.Estudios

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estudios</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagem)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TI2Project/TI2Project/Views/Estudios/Details.cshtml
@model TI2Project.Models.Estudios

<h2>@Html.DisplayFor(model => model.Nome)</h2>

@*impede que utilizadores que não sejam administradores editem ou apaguem estúdios*@
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID })
    </p>
}

<div style="float:left">
    <img src="~/Images/Studios/@Html.DisplayFor(model => model.Imagem)" width="260" height="370">
    <p></p>
    <p>@Html.ActionLink("Back to Studios", "Index")</p> @*botão para regressar ao index dos estúdios*@
</div>

<div style="float:left; border-style:solid; border-color:white; border-width:thick"></div>
<div style="float:left">
    <p><b>Films:</b></p>
    @*cria um parágrafo com a imagem e titulo de cada filme produzido pelo estúdio*@
    @foreach (var item in Model.ListaDeFilmes)
    {
    <p>
        @*redireciona o utilizador para a view Details do filme escolhido*@
        <a href="/Filmes/Details/@item.ID">
            <img src="~/Images/Films/@Html.DisplayFor(modelItem => item.Imagem)" width="50" height="75">
        </a>
        @Html.DisplayFor(modelItem => item.Titulo)
    </p>
    }
</div>

TI2Project/TI2Project/Views/Estudios/Edit.cshtml
@model TI2Project.Models.Estudios

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Estudios", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estudios</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="foto" />
                @*@Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TI2Project/TI2Project/Views/Estudios/Index.cshtml
@model IEnumerable<TI2Project.Models.Estudios>

<h2>Studios</h2>

@*impede que utilizadores que não sejam administradores criem estúdios*@
@if (User.IsInRole("Admin"))
{
    <p>@Html.ActionLink("Add Studio", "Create")</p>
}

@foreach (var item in Model)
{
    <div style="float:left; border-style:solid; border-color:black">
        @*redireciona o utilizador para a view Details do estúdio escolhido*@
        <a href="/Estudios/Details/@item.ID">
            <img src="~/Images/Studios/@item.Imagem" width="180" height="270">
        </a>
        <p style="text-align:center">@item.Nome</p>
    </div>
    <div style="float:left; border-style:solid; border-color:white; border-width:thin"></div>
}