TI2Project/TI2Project/Models/Atores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TI2Project.Models{

    public class Atores{

        public Atores()
        {
            ListaDePersonagens = new HashSet<AtoresFilmes>();
        }

        //atributos de cada ator: id, nome, data de nascimento, nacionalidade e fotografia
        public int ID { get; set; }

        [Required(ErrorMessage = "Write actor's name.")]
        [Display(Name = "Name")]
        public string Nome { get; set; }

        [Display(Name = "Birth Date")]
        public string Nascimento { get; set; }

        [Display(Name = "Nationality")]
        public string Nacionalidade { get; set; }

        [Display(Name = "Photo")]
        public string Foto { get; set; }

        public virtual ICollection<AtoresFilmes> ListaDePersonagens { get; set; } //personagens interpretadas pelo ator
    }
}

TI2Project/TI2Project/Controllers/AtoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TI2Project.Models;

namespace TI2Project.Controllers
{
    public class AtoresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Atores
        public ActionResult Index()
        {
            return View(db.Atores.ToList());
        }

        // GET: Atores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Atores ator = db.Atores.Find(id);
            if (ator == null)
            {
                return RedirectToAction("Index");
            }
            return View(ator);
        }

        // GET: Atores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Atores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome,Nascimento,Nacionalidade")] Atores ator, HttpPostedFileBase foto)
        {
            //variáveis auxiliares
            string caminho = "";
            bool ficheiroValido = false;

            //verifica se foi escolhida alguma imagem
            if (foto == null)
            {
                //atribui uma imagem em branco por defeito
                ator.Foto = "no_image.png";
            }
            else
            {
                string mimeType = foto.ContentType; //identificar o tipo de ficheiro

                //verifica se o ficheiro é jpg ou png
                if (mimeType == "image/jpeg" || mimeType == "image/png")
                {
                    Guid g;
                    g = Guid.NewGuid(); // obtem os dados para o nome do ficheiro

                    string extensao = Path.GetExtension(foto.FileName).ToLower(); //extensão do ficheiro

                    string nomeFicheiro = g.ToString() + extensao; // criar o nome do ficheiro

                    caminho = Path.Combine(Server.MapPath("~/Images/Actors/"), nomeFicheiro); //guarda o caminho do ficheiro

                    ator.Foto = nomeFicheiro;  //atribuir o nome do ficheiro à imagem do filme

                    ficheiroValido = true; //o ficheiro é válido
                }
                else
                {
                    ator.Foto = "no_image.png";
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    db.Atores.Add(ator);
                    db.SaveChanges();

                    if (ficheiroValido) foto.SaveAs(caminho); //se o ficheiro for válido guarda a imagem

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }

            }

            return View(ator);
        }

        // GET: Atores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Atores ator = db.Atores.Find(id);
            if (ator == null)
            {
                return RedirectToAction("Index");
            }
            return View(ator);
        }

        // POST: Atores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Nascimento,Nacionalidade")] Atores ator, HttpPostedFileBase foto)
        {
            string caminho = "";
            bool ficheiroValido = false;

            if (foto == null)
            {
                ator.Foto = "no_image.png";
            }
            else
            {
                string mimeType = foto.ContentType;

                if (mimeType == "image/jpeg" || mimeType == "image/png")
                {
                    Guid g;
                    g = Guid.NewGuid();

                    string extensao = Path.GetExtension(foto.FileName).ToLower();

                    string nomeFicheiro = g.ToString() + extensao;

                    caminho = Path.Combine(Server.MapPath("~/Images/Actors/"), nomeFicheiro);

                    ator.Foto = nomeFicheiro;

                    ficheiroValido = true;
                }
                else
                {
                    ator.Foto = "no_image.png";
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(ator).State = EntityState.Modified;
                    db.SaveChanges();

                    if (ficheiroValido) foto.SaveAs(caminho);

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }

            }
            return View(ator);
        }

        // GET: Atores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Atores ator = db.Atores.Find(id);
            if (ator == null)
            {
                return RedirectToAction("Index");
            }
            return View(ator);
        }

        // POST: Atores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Atores ator = db.Atores.Find(id);
            db.Atores.Remove(ator);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TI2Project/TI2Project/Views/Atores/Create.cshtml
@model TI2Project.Models.Atores

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Atores", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atores</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="foto" />
                @*@Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TI2Project/TI2Project/Views/Atores/Delete.cshtml
@model TI2Project.Models.Atores

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Atores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TI2Project/TI2Project/Views/Atores/Details.cshtml
@model TI2Project.Models.Atores

<h2>@Html.DisplayFor(model => model.Nome)</h2>

@*impede que utilizadores que não sejam administradores editem ou apaguem atores*@
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID })
    </p>
}

    <div style="float:left">
        <img src="~/Images/Actors/@Html.DisplayFor(model => model.Foto)" width="260" height="370">
        <p></p>
        <p>@Html.ActionLink("Back to Actors", "Index")</p> @*botão para regressar ao index dos atores*@
    </div>

@*div com os atributos do ator*@
<div style="float:left; border-style:solid; border-color:white; border-width:thick"></div>
<div style="float:left">
    <p><b>Nacionality:</b> @Html.DisplayFor(model => model.Nacionalidade)</p>
    <p><b>Born at:</b> @Html.DisplayFor(model => model.Nascimento)</p>
</div>

<div style="float:left; border-style:solid; border-color:white; border-width:thick"></div>
<div style="float:left">
    <p><b>Films:</b></p>
    @*cria um parágrafo com a imagem e titulo de cada filme em que o ator participou*@
    @foreach (var item in Model.ListaDePersonagens)
    {
    <p>
        @*redireciona o utilizador para a view Details do filme escolhido*@
        <a href="/Filmes/Details/@item.Filme.ID">
            <img src="~/Images/Films/@Html.DisplayFor(modelItem => item.Filme.Imagem)" width="50" height="75">
        </a>
        @Html.DisplayFor(modelItem => item.Filme.Titulo)
    </p>
    }
</div>

TI2Project/TI2Project/Views/Atores/Edit.cshtml
@model TI2Project.Models.Atores

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Atores", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atores</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="foto" />
                @*@Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TI2Project/TI2Project/Views/Atores/Index.cshtml
@model IEnumerable<TI2Project.Models.Atores>

<h2>Actors</h2>

@*impede que utilizadores que não sejam administradores criem atores*@
@if (User.IsInRole("Admin"))
{
    <p>@Html.ActionLink("Add Actor", "Create")</p>
}

    @foreach (var item in Model)
    {
        <div style="float:left; border-style:solid; border-color:black">
            @*redireciona o utilizador para a view Details do ator escolhido*@
            <a href="/Atores/Details/@item.ID">
                <img src="~/Images/Actors/@item.Foto" width="180" height="270">
            </a>
            <p style="text-align:center">@item.Nome</p>
        </div>
        <div style="float:left; border-style:solid; border-color:white; border-width:thin"></div>
    }