TI2Project/TI2Project/Models/Filmes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TI2Project.Models{

    public class Filmes{

        public Filmes()
        {
            ListaDePersonagens = new HashSet<AtoresFilmes>();
            ListaDeComentarios = new HashSet<Comentarios>();
        }

        //atributos de cada filme: id, titulo, imagem, trailer, ano de lançamento, género e duração (em minutos)
        public int ID { get; set; }

        [Required(ErrorMessage = "Write the movie's name.")]
        [Display(Name = "Title")]
        public string Titulo { get; set; }

        [Display(Name = "Image")]
        public string Imagem { get; set; }

        public string Trailer { get; set; } //id correspondente ao video no youtube

        [Display(Name = "Release Year")]
        [Required(ErrorMessage = "Release year is needed.")]
        public int Lancamento { get; set; }

        [Display(Name = "Genre")]
        public string Genero { get; set; }

        [Required(ErrorMessage = "Movie length is needed.")]
        [Display(Name = "Duration (in mins)")]
        public int Duracao { get; set; }

        //chave forasteira do estúdio que produziu o filme
        [ForeignKey("Estudio")]
        public int EstudioFK { get; set; }
        public virtual Estudios Estudio { get; set; }

        public virtual ICollection<AtoresFilmes> ListaDePersonagens { get; set; } //personagens que aparecem no filme

        public virtual ICollection<Comentarios> ListaDeComentarios { get; set; } //comentários acerca do filme
    }
}

TI2Project/TI2Project/Controllers/AtoresFilmesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TI2Project.Models;

namespace TI2Project.Controllers
{
    public class AtoresFilmesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AtoresFilmes
        public ActionResult Index()
        {
            var atorFilme = db.AtoresFilmes.Include(a => a.Ator).Include(a => a.Filme);
            return View(atorFilme.ToList());
        }

        // GET: AtoresFilmes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            AtoresFilmes atorFilme = db.AtoresFilmes.Find(id);
            if (atorFilme == null)
            {
                return RedirectToAction("Index");
            }
            return View(atorFilme);
        }

        // GET: AtoresFilmes/Create
        public ActionResult Create()
        {
            ViewBag.AtorFK = new SelectList(db.Atores, "ID", "Nome");
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo");
            return View();
        }

        // POST: AtoresFilmes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NomePersonagem,AtorFK,FilmeFK")] AtoresFilmes atoresFilmes)
        {
            if (ModelState.IsValid)
            {
                db.AtoresFilmes.Add(atoresFilmes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AtorFK = new SelectList(db.Atores, "ID", "Nome", atoresFilmes.AtorFK);
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", atoresFilmes.FilmeFK);
            return View(atoresFilmes);
        }

        // GET: AtoresFilmes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            AtoresFilmes atoresFilmes = db.AtoresFilmes.Find(id);
            if (atoresFilmes == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.AtorFK = new SelectList(db.Atores, "ID", "Nome", atoresFilmes.AtorFK);
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", atoresFilmes.FilmeFK);
            return View(atoresFilmes);
        }

        // POST: AtoresFilmes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NomePersonagem,AtorFK,FilmeFK")] AtoresFilmes atoresFilmes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(atoresFilmes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AtorFK = new SelectList(db.Atores, "ID", "Nome", atoresFilmes.AtorFK);
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", atoresFilmes.FilmeFK);
            return View(atoresFilmes);
        }

        // GET: AtoresFilmes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            AtoresFilmes atoresFilmes = db.AtoresFilmes.Find(id);
            if (atoresFilmes == null)
            {
                return RedirectToAction("Index");
            }
            return View(atoresFilmes);
        }

        // POST: AtoresFilmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AtoresFilmes atoresFilmes = db.AtoresFilmes.Find(id);
            db.AtoresFilmes.Remove(atoresFilmes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TI2Project/TI2Project/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TI2Project.Models;

namespace TI2Project.Controllers
{
    public class ComentariosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comentarios
        public ActionResult Index()
        {
            var comentario = db.Comentarios.Include(c => c.Filme);
            return View(comentario.ToList());
        }

        // GET: Comentarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Comentarios comentarios = db.Comentarios.Find(id);
            if (comentarios == null)
            {
                return RedirectToAction("Index");
            }
            return View(comentarios);
        }

        // GET: Comentarios/Create
        public ActionResult Create()
        {
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo");
            return View();
        }

        // POST: Comentarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Conteudo,FilmeFK")] Comentarios comentarios)
        {
            //atribui a cada comentário, a data em que o mesmo foi criado
            comentarios.Data = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Comentarios.Add(comentarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", comentarios.FilmeFK);
            return View(comentarios);
        }

        // GET: Comentarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Comentarios comentarios = db.Comentarios.Find(id);
            if (comentarios == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", comentarios.FilmeFK);
            return View(comentarios);
        }

        // POST: Comentarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Conteudo,FilmeFK")] Comentarios comentarios)
        {
            //atribui a cada comentário, a data em que o mesmo foi editado
            comentarios.Data = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Entry(comentarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", comentarios.FilmeFK);
            return View(comentarios);
        }

        // GET: Comentarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Comentarios comentarios = db.Comentarios.Find(id);
            if (comentarios == null)
            {
                return RedirectToAction("Index");
            }
            return View(comentarios);
        }

        // POST: Comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comentarios comentarios = db.Comentarios.Find(id);
            db.Comentarios.Remove(comentarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TI2Project/TI2Project/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TI2Project.Models;

namespace TI2Project.Controllers
{
    public class FilmesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Filmes
        public ActionResult Index()
        {
            var filme = db.Filmes.Include(f => f.Estudio);
            return View(filme.ToList());
        }

        // GET: Filmes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Filmes filme = db.Filmes.Find(id);
            if (filme == null)
            {
                return RedirectToAction("Index");
            }
            return View(filme);
        }

        // GET: Filmes/Create
        public ActionResult Create()
        {
            ViewBag.EstudioFK = new SelectList(db.Estudios, "ID", "Nome");
            return View();
        }

        // POST: Filmes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Titulo,Trailer,Lancamento,Genero,Duracao,EstudioFK")] Filmes filme, HttpPostedFileBase foto)
        {
            //variáveis auxiliares
            string caminho = "";
            bool ficheiroValido = false;

            //verifica se foi escolhida alguma imagem
            if (foto == null)
            {
                //atribui uma imagem em branco por defeito
                filme.Imagem = "no_image.png";
            }
            else
            {
                string mimeType = foto.ContentType; //identificar o tipo de ficheiro

                //verifica se o ficheiro é jpg ou png
                if (mimeType == "image/jpeg" || mimeType == "image/png")
                {
                    Guid g;
                    g = Guid.NewGuid(); // obtem os dados para o nome do ficheiro

                    string extensao = Path.GetExtension(foto.FileName).ToLower(); //extensão do ficheiro

                    string nomeFicheiro = g.ToString() + extensao; // criar o nome do ficheiro

                    caminho = Path.Combine(Server.MapPath("~/Images/Films/"), nomeFicheiro); //guarda o caminho do ficheiro

                    filme.Imagem = nomeFicheiro; //atribuir o nome do ficheiro à imagem do filme

                    ficheiroValido = true; //o ficheiro é válido
                }
                else
                {
                    filme.Imagem = "no_image.png";
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    db.Filmes.Add(filme);
                    db.SaveChanges();

                    if (ficheiroValido) foto.SaveAs(caminho); //se o ficheiro for válido guarda a imagem

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }

            }
            

            ViewBag.EstudioFK = new SelectList(db.Estudios, "ID", "Nome", filme.EstudioFK);
            return View(filme);
        }

        // GET: Filmes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Filmes filmes = db.Filmes.Find(id);
            if (filmes == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.EstudioFK = new SelectList(db.Estudios, "ID", "Nome", filmes.EstudioFK);
            return View(filmes);
        }

        // POST: Filmes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,Trailer,Lancamento,Genero,Duracao,EstudioFK")] Filmes filme, HttpPostedFileBase foto)
        {
            string caminho = "";
            bool ficheiroValido = false;

            if (foto == null)
            {
                filme.Imagem = "no_image.png";
            }
            else
            {
                string mimeType = foto.ContentType;

                if (mimeType == "image/jpeg" || mimeType == "image/png")
                {
                    Guid g;
                    g = Guid.NewGuid();

                    string extensao = Path.GetExtension(foto.FileName).ToLower();

                    string nomeFicheiro = g.ToString() + extensao;

                    caminho = Path.Combine(Server.MapPath("~/Images/Films/"), nomeFicheiro);

                    filme.Imagem = nomeFicheiro;

                    ficheiroValido = true;
                }
                else
                {
                    filme.Imagem = "no_image.png";
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(filme).State = EntityState.Modified;
                    db.SaveChanges();

                    if (ficheiroValido) foto.SaveAs(caminho);

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }

            }


            ViewBag.EstudioFK = new SelectList(db.Estudios, "ID", "Nome", filme.EstudioFK);
            return View(filme);
        }

        // GET: Filmes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Filmes filme = db.Filmes.Find(id);
            if (filme == null)
            {
                return RedirectToAction("Index");
            }
            return View(filme);
        }

        // POST: Filmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Filmes filme = db.Filmes.Find(id);
            db.Filmes.Remove(filme);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TI2Project/TI2Project/Views/Filmes/Create.cshtml
@model TI2Project.Models.Filmes

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Filmes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filmes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="foto" />
                @*@Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lancamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lancamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lancamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstudioFK, "EstudioFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstudioFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstudioFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TI2Project/TI2Project/Views/Filmes/Details.cshtml
@model TI2Project.Models.Filmes

<h2>@Html.DisplayFor(model => model.Titulo)</h2>

@*impede que utilizadores que não sejam administradores editem ou apaguem filmes*@
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID })
    </p>
}

<div style="float:left">
    <img src="~/Images/Films/@Html.DisplayFor(model => model.Imagem)" width="260" height="370">
    <p></p>
    <p>@Html.ActionLink("Back to Films", "Index")</p> @*botão para regressar ao index dos filmes*@
</div>

@*div com os atributos do filme*@
<div style="float:left; border-style:solid; border-color:white; border-width:thick"></div>
<div style="float:left">
    <p><b>Duration:</b> @Html.DisplayFor(model => model.Duracao) mins</p>
    <p><b>Genre:</b> @Html.DisplayFor(model => model.Genero)</p>
    <p><b>Year:</b> @Html.DisplayFor(model => model.Lancamento)</p>
    <p>
        <b>Studio:</b>
        @*redireciona o utilizador para a view Details do estúdio que produziu o filme*@
        <a href="/Estudios/Details/@Html.DisplayFor(model => model.Estudio.ID)">
            <img src="~/Images/Studios/@Html.DisplayFor(model => model.Estudio.Imagem)" width="50" height="75">
        </a>
        @Html.DisplayFor(model => model.Estudio.Nome)
    </p>
    <p><b>Trailer:</b></p>
    @*cria uma janela onde se pode ver o video do link corresponde ao trailer do filme*@
    <iframe width="250" height="150" src="https://www.youtube.com/embed/@Html.DisplayFor(model => model.Trailer)" allowfullscreen></iframe>
</div>

<div style="float:left; border-style:solid; border-color:white; border-width:thick"></div>
<div style="float:left">
    <p><b>Characters:</b></p>
    @*impede que utilizadores que não sejam administradores criem personagens*@
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Add Character", "Create", "AtoresFilmes")
    }
    @*cria um parágrafo com a imagem e titulo de cada ator que participa no filme, e a personagem que interpreta*@
    @foreach (var item in Model.ListaDePersonagens)
    {
    <p>
        @*redireciona o utilizador para a view Details do do ator escolhido*@
        <a href="/Atores/Details/@item.Ator.ID">
            <img src="~/Images/Actors/@Html.DisplayFor(modelItem => item.Ator.Foto)" width="50" height="75">
        </a>
        @Html.DisplayFor(modelItem => item.Ator.Nome) as
        @Html.DisplayFor(modelItem => item.NomePersonagem)
    </p>
        @*impede que utilizadores que não sejam administradores editem ou apaguem personagens*@
        if (User.IsInRole("Admin"))
        {
            <p>
                @Html.ActionLink("Edit", "Edit", "AtoresFilmes", new { id = item.ID }, null) |
                @Html.ActionLink("Delete", "Delete", "AtoresFilmes", new { id = item.ID }, null)
            </p>
        }
    }
</div>

<div style="float:left; border-style:solid; border-color:white; border-width:thick"></div>
<div style="float:left">
    <p><b>Coments:</b></p>
    @*impede que utilizadores anónimos criem comentários*@
    @if (User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Add Coment", "Create", "Comentarios")
    }
    @*mostra todos os comentários correspondetne ao filme atual*@
    @foreach (var item in Model.ListaDeComentarios)
    {
        <p>@Html.DisplayFor(modelItem => item.Conteudo) <small>@Html.DisplayFor(modelItem => item.Data)</small></p>
        @*impede que utilizadores que não sejam administradores apaguem comentários*@
        if (User.IsInRole("Admin"))
        {
            <p>
                @*@Html.ActionLink("Edit", "Edit", "Comentarios", new { id = item.ID }, null) |*@
                @Html.ActionLink("Delete", "Delete", "Comentarios", new { id = item.ID }, null)
            </p>
        }
    }
</div>

TI2Project/TI2Project/Views/Filmes/Edit.cshtml
@model TI2Project.Models.Filmes

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Filmes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filmes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="foto" />
                @*@Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lancamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lancamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lancamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstudioFK, "EstudioFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstudioFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstudioFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}